### ISSUE TITLE
Collaborate in one fork

### ISSUE THREAD

**Issue by davidak** [henricj/audacity#5]
There is one popular fork that is maintained, but looks for collaborators:

https://github.com/cookiengineer/audacity
https://fosspost.org/audacity-fork-needs-help/

I suggest you archive this repo, add a link to that fork and contribute there if you want. It does not make sense to maintain multiple forks with the same goal.

Thanks for your efforts improving free software!

**Comment by henricj** [comment]
The goals here were more about 64-bit Windows support (including for ARM) and simplifying the overly-complicated build process in the parent repo.

At this point, this fork is so far behind (over 1200 commits behind Audacity's master) and has so many local changes (more than 80 commits ahead of Audacity master) that it would take a huge effort to sync things up.

The TL;DR for the Windows side:
1. Don't use the MSBuild infrastructure (by using a separate CMake to generate .cxproj files); open the folder directly with VS2019 and it will do CMake/Ninja automatically (or build directly with cmake on the command line).  There is nothing inherently wrong with MSBuild, but there is no good reason for having CMake generate files for a different build system on Windows than on Linux.
2. Make sure to set /utf-8, /permissive-, and probably /volatile:iso when compiling with MSVC for better standards compliance and to be more consistent with other compilers.
3. Build with a current WIndows SDK (even when targeting earlier versions of Windows).
4. Think carefully about how to manage the C++ runtime.  Including private copies of the DLLs means that plugin authors should either make very sure they are building against a version of the C++ runtime no newer than what was used to build any of the versions of the not-called-Audacity-anymore executable they are targeting, or they should service the C++ runtime in some way as part of their install.  The sanest way is to have the installs (both for the main app and any plugins) run Microsoft's C++ redist installer.  It will make sure the C++ runtime is up-to-date and that the C runtime is set up properly (relevant for older versions of Windows).  The goal is to make sure that the C++ runtime DLLs that get loaded into memory are no older than what any of the other DLLs or EXE were linked against.  Using a version of the C++ runtime DLLs older than what was used for the build is not supported and can lead to the worst kinds of Heisenbugs.

**Comment by davidak** [comment]
@henricj thank you for the response!

I linked it in the other fork.

**Comment by PlavorSeol** [comment]
Note that this user also spammed [an issue](https://github.com/SartoxOnlyGNU/audacium/issues/3) on another repository with almost same content.
